-- =========================================================================
-- CURSO 1: HTML (Módulos restantes: 3, 4 y 5)
-- =========================================================================

-- Módulo 3: Formularios (id_module = 3)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(24, 'La etiqueta Form y campos de texto', 'Un formulario se define con la etiqueta <form>, que actúa como un contenedor general para capturar datos. El campo más común es <input type="text"> para textos cortos de una línea. Siempre se debe acompañar de una etiqueta <label> para describir de manera accesible qué información se solicita.', '<form>\n  <label>Nombre de usuario:</label>\n  <input type="text">\n</form>', 'html'),
(23, 'Entradas de datos especializadas (Contraseñas y Emails)', 'Modificando el atributo "type" de un <input> le damos superpoderes semánticos. Usar type="password" enmascara los caracteres automáticamente para proteger datos sensibles. Usar type="email" obliga al navegador a validar que el formato ingresado contenga un arroba y un dominio válido.', '<form>\n  <label>Correo Electrónico:</label>\n  <input type="email">\n  <br><br>\n  <label>Contraseña:</label>\n  <input type="password">\n</form>', 'html'),
(25, 'Opciones de selección (Radio y Checkbox)', 'Para opciones cerradas usamos tipos específicos. El input type="checkbox" crea casillas cuadradas que permiten una selección múltiple. El input type="radio" crea botones redondos de opción única; para agruparlos y hacer que al marcar uno se desmarque otro, debes asignarles exactamente el mismo atributo "name".', '<form>\n  <p>Elige tus intereses:</p>\n  <input type="checkbox"> Programación\n  <input type="checkbox"> Diseño\n  <p>¿Aceptas las condiciones?</p>\n  <input type="radio" name="politica"> Sí\n  <input type="radio" name="politica"> No\n</form>', 'html'),
(26, 'Listas desplegables y áreas de texto', 'Cuando las opciones son numerosas, la etiqueta <select> crea un menú desplegable eficiente donde cada opción se define con <option>. Si lo que necesitas es que el usuario redacte un texto largo, opiniones o párrafos enteros, se utiliza la etiqueta contenedora de múltiples líneas <textarea>.', '<form>\n  <label>País:</label>\n  <select>\n    <option>España</option>\n    <option>México</option>\n  </select>\n  <br><br>\n  <label>Comentarios:</label><br>\n  <textarea rows="3" cols="30"></textarea>\n</form>', 'html'),
(27, 'El botón de envío (Submit)', 'Todo formulario necesita un disparador para procesar los datos capturados. Al usar un elemento <button type="submit"> o un <input type="submit"> dentro de las etiquetas de formulario, indicamos al navegador que empaquete toda la información y realice la acción de envío del formulario.', '<form>\n  <label>Buscar:</label>\n  <input type="text">\n  <button type="submit">Enviar datos</button>\n</form>', 'html');

-- Módulo 4: Multimedia (id_module = 4)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(28, 'Insertar Imágenes', 'La etiqueta autocerrada <img> nos permite incrustar imágenes en la página web. Requiere dos atributos esenciales: "src", que apunta a la URL o ruta local del archivo de imagen, y "alt", que proporciona una descripción textual de la imagen para lectores de pantalla y optimización SEO.', '<img src="https://images.unsplash.com/photo-1517694712202-14dd9538aa97" alt="Ordenador portátil con código en pantalla" width="300">', 'html'),
(29, 'Incorporar Audio', 'La etiqueta <audio> permite reproducir archivos de sonido (como .mp3). Es indispensable agregar el atributo "controls" para que el navegador dibuje la barra de herramientas nativa con los botones de reproducción, pausa y volumen.', '<audio src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" controls>\n  Tu navegador no soporta elementos de audio.\n</audio>', 'html'),
(30, 'Incorporar Video', 'Para incrustar archivos multimedia de video se utiliza la etiqueta <video>. Al igual que el audio, requiere el atributo "controls". Podemos manipular sus dimensiones en pantalla directamente mediante los atributos "width" and "height" expresados en píxeles.', '<video src="https://www.w3schools.com/html/mov_bbb.mp4" controls width="320" height="240">\n  Tu navegador no soporta videos.\n</video>', 'html');

-- Módulo 5: HTML semántico (id_module = 5)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(31, '¿Qué es la semántica y por qué importa?', 'El HTML semántico consiste en utilizar las etiquetas adecuadas según el significado real de su contenido, en lugar de usar divs genéricos para todo. Esto ayuda drásticamente a que los motores de búsqueda indexen correctamente tu web y permite que las herramientas de asistencia de accesibilidad entiendan el contexto.', '<article>\n  <h2>Introducción al desarrollo web</h2>\n  <p>La semántica da significado claro al contenido de la página.</p>\n</article>', 'html'),
(32, 'Estructura principal (Header, Nav, Footer)', 'Cualquier maquetación profesional se divide en bloques semánticos globales. El <header> define la cabecera del sitio (logos o títulos). El elemento <nav> agrupa los enlaces principales de navegación y menús. El <footer> delimita el pie de página con datos institucionales y de derechos reservados.', '<header>\n  <h1>Portal de Noticias</h1>\n  <nav>\n    <a href="#">Inicio</a> | <a href="#">Contacto</a>\n  </nav>\n</header>\n<footer>\n  <p>© 2026 Todos los derechos reservados.</p>\n</footer>', 'html'),
(33, 'Contenido principal (Main, Section, Article)', 'Para estructurar el núcleo de información de la página usamos <main>, que encierra el contenido único y principal del sitio. Dentro de él, usamos <section> para agrupar temáticas o bloques lógicos, y <article> para elementos independientes y autocontenidos que tendrían sentido por sí mismos (como un post).', '<main>\n  <section>\n    <h2>Últimos artículos</h2>\n    <article>\n      <h3>Aprendiendo HTML</h3>\n      <p>Guía de etiquetas semánticas fundamentales.</p>\n    </article>\n  </section>\n</main>', 'html'),
(34, 'Contenido secundario y bloques (Aside)', 'La etiqueta <aside> representa contenido que está indirectamente relacionado con el contenido principal a su alrededor. Se suele utilizar comúnmente para maquetar barras laterales de navegación secundaria, bloques de publicidad, widgets de redes sociales o glosarios adicionales.', '<main>\n  <h1>Artículo Principal</h1>\n  <p>Contenido central de la publicación de tecnología.</p>\n</main>\n<aside>\n  <h4>Enlaces patrocinados</h4>\n  <p>Anuncios de servidores y hosting de bases de datos.</p>\n</aside>', 'html');


-- =========================================================================
-- CURSO 2: CSS (id_course = 2)
-- =========================================================================

-- Módulo 7: Selectores (id_module = 7)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(35, 'Selectores Básicos', 'Los selectores de CSS vinculan las reglas de diseño con las etiquetas HTML. Los tres selectores básicos son: por tipo de etiqueta (ej. h1), por clase utilizando un punto (.mi-clase) aplicable a múltiples elementos, y por identificador usando un hashtag (#mi-id) que es estrictamente único por página.', '/* Estilos en CSS */\nh1 { color: #2c3e50; }\n.texto-azul { color: blue; }\n#alerta-principal { background-color: red; }', 'css'),
(36, 'Selectores Combinadores', 'Los combinadores nos permiten refinar la puntería uniendo selectores en base a su relación en el árbol HTML. El combinador de descendientes (un espacio en blanco) afecta a un elemento dentro de otro. El combinador de hijos directos (>) afecta únicamente a las etiquetas que se encuentran en el primer nivel inferior de jerarquía.', '/* Selecciona cualquier "span" dentro de un "div" */\ndiv span { font-weight: bold; }\n/* Selecciona solo "span" que sea hijo directo de "div" */\ndiv > span { color: green; }', 'css'),
(37, 'Pseudo-clases y Pseudo-elementos', 'Las pseudo-clases definen estados específicos de un elemento, como cuando pasas el cursor encima (:hover). Los pseudo-elementos sirven para estilizar partes específicas de un componente, como la primera línea de un párrafo o añadir un decorador virtual antes (:before) o después (:after) de su contenido.', '/* Cambia el color de un botón cuando pasas el cursor */\nbutton:hover {\n  background-color: darkblue;\n}\n/* Añade un asterisco decorativo antes de un párrafo */\np::before {\n  content: "★ ";\n}', 'css');

-- Módulo 8: Box Model (id_module = 8)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(38, 'Dimensiones y Espaciados (Padding y Margin)', 'El Modelo de Caja dicta que cada elemento es un rectángulo. Controlamos su tamaño con "width" (ancho) y "height" (alto). El "padding" es el espaciado interno que separa el contenido de sus propios bordes, mientras que el "margin" es el espaciado externo que separa a este elemento de las cajas vecinas.', '.caja {\n  width: 200px;\n  height: 100px;\n  padding: 20px;\n  margin: 30px;\n  background-color: lightgray;\n}', 'css'),
(39, 'Bordes y Estilos Exteriores', 'La propiedad "border" define la línea perimetral de un elemento y requiere tres valores: grosor, estilo (solid, dashed, dotted) and color. También puedes redondear las esquinas de tu caja utilizando la propiedad "border-radius" expresada en píxeles o porcentajes.', '.tarjeta {\n  border: 2px dashed #ff5722;\n  border-radius: 8px;\n  padding: 10px;\n}', 'css'),
(40, 'La propiedad Box-Sizing', 'Por defecto, si agregas padding o border a una caja, su tamaño total aumenta rompiendo la maquetación. Cambiar la propiedad "box-sizing: border-box" soluciona esto, obligando al navegador a incluir el grosor del borde y del padding dentro de las medidas exactas de ancho y alto especificadas.', '/* Configuración recomendada para todos los elementos */\n* {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}', 'css');

-- Módulo 9: Flexbox (id_module = 9)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(41, 'El Contenedor Flex', 'Flexbox es un sistema de alineación unidimensional (filas o columnas). Al declarar "display: flex;" en un elemento contenedor, sus hijos directos se convierten automáticamente en elementos flexibles (flex items), posicionándose uno al lado del otro por defecto en un eje horizontal.', '.contenedor {\n  display: flex;\n  background-color: #333;\n}', 'css'),
(42, 'Alineación y Distribución de Espacios', 'En un contenedor flexbox controlamos la alineación en ambos ejes. La propiedad "justify-content" distribuye el espacio horizontalmente (valores como center, space-between, space-around). La propiedad "align-items" controla la alineación en el eje vertical (como center, stretch, flex-start).', '.menu-navegacion {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}', 'css'),
(43, 'Propiedades de los Elementos Hijos (Flex Items)', 'Los elementos hijos dentro de un contenedor flex pueden controlar su comportamiento individual. Usamos "flex-grow" para indicar si una caja puede crecer para ocupar el espacio sobrante, "flex-shrink" para controlar cómo se encoge, y "align-self" para anular la alineación vertical general heredada del padre.', '.item-expandible {\n  flex-grow: 1;\n  align-self: flex-end;\n}', 'css');

-- Módulo 10: Grid (id_module = 10)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(44, 'Definición de Filas y Columnas', 'CSS Grid es un sistema bidimensional (filas y columnas de forma simultánea). Activando "display: grid;" podemos segmentar el espacio. Usamos "grid-template-columns" y "grid-template-rows" usando unidades fijas o la unidad de fracción flexible "fr". Añadimos separación con la propiedad "gap".', '.rejilla-productos {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 15px;\n}', 'css'),
(45, 'Posicionamiento de Elementos', 'Puedes indicarle a un elemento hijo dentro de una cuadrícula exactamente qué celdas debe abarcar. Usamos las líneas de cuadrícula con las propiedades "grid-column-start/end" (o de forma abreviada grid-column) y lo mismo para las filas con grid-row.', '.banner-ancho {\n  /* Empieza en la línea de columna 1 y se extiende hasta la 4 (ocupa 3 columnas) */\n  grid-column: 1 / 4;\n}', 'css'),
(46, 'Áreas de Grid y Responsive', 'Una forma muy visual de maquetar es nombrar zonas usando la propiedad "grid-template-areas" en el contenedor. Posteriormente asignas a cada elemento hijo su sección correspondiente con "grid-area". Esto simplifica drásticamente reordenar los componentes estructurales en pantallas móviles.', '.layout {\n  display: grid;\n  grid-template-areas:\n    "header header"\n    "sidebar main";\n}\n.mi-cabecera { grid-area: header; }', 'css');

-- Módulo 11: Animaciones (id_module = 11)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(47, 'Transiciones Fluidas', 'La propiedad "transition" permite suavizar el cambio de propiedades de CSS cuando ocurre un evento (como pasar el mouse). Requiere definir qué propiedad animar, la duración en segundos y la curva de aceleración (ease, linear, etc.).', '.boton-interactivo {\n  background-color: gray;\n  transition: background-color 0.4s ease-in-out;\n}\n.boton-interactivo:hover {\n  background-color: orange;\n}', 'css'),
(48, 'Animaciones Avanzadas con @keyframes', 'Para animaciones complejas que no dependen de la interacción directa del usuario, creamos una línea de tiempo usando la regla "@keyframes" junto con un nombre asignado. Dentro definimos los porcentajes del recorrido (0% al 100%) y los cambios visuales, para luego invocarla con la propiedad "animation".', '@keyframes rotar {\n  from { transform: rotate(0deg); }\n  to { transform: rotate(360deg); }\n}\n.icono-carga {\n  animation: rotar 2s linear infinite;\n}', 'css');


-- =========================================================================
-- CURSO 3: JAVASCRIPT (id_course = 3) -> code_lang cambiado a 'js'
-- =========================================================================

-- Módulo 13: Variables y tipos (id_module = 13)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(49, 'Declaración de Variables: let vs const', 'Las variables almacenan valores de información. En el estándar moderno de JavaScript, usamos "let" cuando el valor de la variable mutará o cambiará a lo largo de la ejecución. Usamos "const" para declarar constantes fijas cuyo valor inicial jamás puede ser reasignado.', 'let contador = 0;\ncontador = 1; \n\nconst pi = 3.1416;\n// pi = 3; // Error', 'js'),
(50, 'Tipos Primitivos de Datos', 'JavaScript detecta automáticamente los tipos de datos al asignarlos. Los tipos primitivos personalizados son: Strings (cadenas de texto), Numbers (valores enteros o decimales) y Booleans (valores lógicos true/false).', 'const usuario = "Carlos"; \nconst edad = 25;           \nconst activo = true;', 'js'),
(51, 'Operadores Matemáticos y Lógicos', 'Permiten realizar cálculos y evaluaciones lógicas. Los matemáticos incluyen suma (+), resta (-), multiplicación (*) y división (/). Los lógicos permiten evaluar condiciones concurrentes mediante el operador AND (&&), el operador OR (||) y el operador de negación (!).', 'let precio = 100;\nlet total = (precio * 1.21) - 5;\nlet puedeEntrar = (total > 50) && true;\nconsole.log(total);', 'js');

-- Módulo 14: Funciones (id_module = 14)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(52, 'Funciones Tradicionales y Parámetros', 'Una función es un bloque aislado de instrucciones reutilizables. Se define con la palabra reservada "function" seguida de un nombre y paréntesis. Dentro de los paréntesis podemos declarar "parámetros", que actúan como variables locales listas para recibir datos del exterior cuando invoquemos la función.', 'function saludarUsuario(nombre) {\n  console.log("Bienvenido de nuevo, " + nombre);\n}\n\nsaludarUsuario("Laura");', 'js'),
(53, 'Retorno de Valores', 'Las funciones no solo ejecutan tareas, también pueden procesar datos y devolver un resultado final hacia el punto exacto de la aplicación donde fueron llamadas. Para lograr esto, se utiliza la palabra clave "return" al final de la lógica de la función.', 'function calcularDoble(numero) {\n  return numero * 2;\n}\n\nlet miResultado = calcularDoble(25);\nconsole.log(miResultado);', 'js');

-- Módulo 15: DOM (id_module = 15)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(54, 'Selección de Elementos del DOM', 'El DOM es la representación que tiene el navegador de tu archivo HTML. Para interactuar con él desde JavaScript, primero debemos capturar los elementos deseados. La herramienta estándar y más potente es "document.querySelector()", la cual utiliza los mismos nombres de selectores que usas en tus hojas de CSS.', 'const titulo = document.querySelector("#titulo-principal");\nconst botones = document.querySelector(".btn-accion");', 'js'),
(55, 'Modificación de Contenidos y Estilos', 'Una vez capturado un nodo del DOM, podemos transformar su apariencia en tiempo real. Usamos la propiedad "textContent" para reemplazar el texto interno de la etiqueta de forma segura, o el objeto ".style" seguido de una propiedad CSS en formato camelCase para alterar el diseño visual de forma dinámica.', 'const banner = document.querySelector("#banner");\nbanner.textContent = "¡Texto modificado con JS!";\nbanner.style.backgroundColor = "gold";', 'js'),
(56, 'Escucha de Eventos (Event Listeners)', 'La interactividad se basa en reaccionar a las acciones del usuario. Usamos el método "addEventListener()" acoplado a un elemento seleccionado. Este método se queda "escuchando" permanentemente el evento indicado (como un "click", "submit" o "keyup") y ejecuta una función automáticamente cuando la acción sucede.', 'const boton = document.querySelector("#miBoton");\nboton.addEventListener("click", () => {\n  alert("¡Hiciste clic en el botón!");\n});', 'js');

-- Módulo 33: Async & Await (id_module = 33)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(60, 'El Concepto de Promesas', 'Una promesa representa un valor que puede estar disponible ahora, en el futuro o nunca, simulando operaciones en diferido (como consultar un servidor). Puede tener tres estados: pendiente (pending), resuelta con éxito (fulfilled) o rechazada con un error (rejected).', 'const miPromesa = new Promise((resolve, reject) => {\n  let exito = true;\n  if(exito) resolve("Datos recibidos");\n  else reject("Error en el sistema");\n});', 'js'),
(61, 'Consumo de APIs con Async y Await', 'Para leer datos asíncronos de forma limpia, usamos las palabras clave "async" y "await". Marcamos la función contenedora como "async" y anteponemos "await" a las funciones que devuelven promesas (como "fetch"). Esto pausa de forma ordenada la ejecución del script hasta que la petición web responda con los datos.', 'async function cargarDatos() {\n  let response = await fetch("https://jsonplaceholder.typicode.com/posts/1");\n  let data = await response.json();\n  console.log(data.title);\n}\ncargarDatos();', 'js');

-- Módulo 17: ES6+ (id_module = 17)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(57, 'Funciones Flecha (Arrow Functions)', 'Las funciones flecha proveen una sintaxis extremadamente compacta y simplificada para escribir funciones en JavaScript, eliminando la necesidad de usar explícitamente la palabra reservada "function". Son ampliamente utilizadas en el desarrollo moderno y en métodos de arrays.', 'const sumar = (a, b) => a + b;\nconsole.log(sumar(5, 10));', 'js'),
(58, 'Template Literals', 'Los Template Literals sustituyen la vieja concatenación con símbolos de suma. Se delimitan utilizando las comillas invertidas (backticks). Nos permiten combinar variables y expresiones directamente dentro del flujo del texto envolviéndolas en la estructura de marcador de posición `${variable}`.', 'const producto = "Teclado";\nconst precio = 45;\nconsole.log(`El artículo ${producto} tiene un costo de $${precio} USD.`);', 'js'),
(59, 'Desestructuración (Destructuring)', 'La desestructuración es una expresión que permite extraer propiedades de objetos o elementos de arreglos directamente hacia variables individuales independientes mediante una sintaxis limpia y directa, evitando tener que escribir líneas repetitivas de asignación.', 'const usuario = { nombre: "Ana", pais: "España", rol: "Editor" };\nconst { nombre, rol } = usuario;\nconsole.log(nombre);', 'js');


-- =========================================================================
-- CURSO 4: PHP (id_course = 4) -> code_lang cambiado a 'php'
-- =========================================================================

-- Módulo 19: Variables y arrays (id_module = 19)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(65, 'Sintaxis de Variables en PHP', 'En PHP todas las variables se definen obligatoriamente con el símbolo de dólar ($) al inicio de su nombre. PHP es un lenguaje de tipado dinámico, lo que significa que no necesitas especificar explícitamente si una variable almacena un texto o un número.', '<?php\n$curso = "Programación Backend";\n$anio = 2026;\necho $curso;\n?>', 'php'),
(66, 'Arrays Indexados y Asociativos', 'Los arrays almacenan múltiples valores bajo una sola variable. Los indexados usan llaves numéricas automáticas (0, 1, 2...). Los asociativos permiten personalizar los índices asignándoles claves textuales mediante el operador flecha (=>), actuando como mapas estructurados de datos.', '<?php\n$usuario = [\n  "nombre" => "Elena",\n  "correo" => "elena@mail.com"\n];\necho $usuario["correo"];\n?>', 'php');

-- Módulo 20: Funciones (id_module = 20)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(67, 'Declaración e Invocación', 'Las funciones aíslan fragmentos de código lógico para ser ejecutados únicamente cuando los llamamos en el script. Se crean usando el comando "function" y pueden opcionalmente retornar datos al flujo principal mediante "return".', '<?php\nfunction duplicarValor($numero) {\n  return $numero * 2;\n}\necho duplicarValor(14);\n?>', 'php'),
(68, 'Ámbito de Variables (Scope)', 'A diferencia de otros lenguajes, las variables globales declaradas fuera de una función en PHP no son accesibles de forma automática dentro del cuerpo de la función. Si necesitas interactuar con una variable externa dentro de un bloque funcional local, debes importarla explícitamente usando la palabra clave "global".', '<?php\n$global_tax = 0.21;\nfunction calcularPrecio($neto) {\n  global $global_tax;\n  return $neto + ($neto * $global_tax);\n}\necho calcularPrecio(100);\n?>', 'php');

-- Módulo 21: Programación orientada a objetos (id_module = 21)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(62, 'Clases and Objetos', 'La POO estructura el código basándose en entidades abstractas del mundo real. Una Clase representa la plantilla o plano de diseño que define los atributos (propiedades) y acciones (métodos). Un Objeto es la realización concreta o instancia construida a partir de dicho plano.', '<?php\nclass Dispositivo {\n  public $tipo;\n}\n$miLaptop = new Dispositivo();\n$miLaptop->tipo = "Computadora";\necho $miLaptop->tipo;\n?>', 'php'),
(63, 'El Método Constructor', 'El constructor es un método mágico especial denominado obligatoriamente "__construct()". Se ejecuta de forma automática e inmediata en el momento preciso en que se instancia un nuevo objeto con la palabra clave "new", siendo ideal para inicializar propiedades esenciales de la clase.', '<?php\nclass Persona {\n  public $nombre;\n  public function __construct($nom) {\n    $this->nombre = $nom;\n  }\n}\n$usuario = new Persona("Roberto");\necho $usuario->nombre;\n?>', 'php'),
(64, 'Modificadores de Acceso (Public y Private)', 'Los modificadores controlan la visibilidad y la seguridad de las propiedades y métodos de una clase. El modificador "public" permite el acceso a los datos desde cualquier parte de la aplicación. El modificador "private" restringe el acceso de forma absoluta, permitiendo leer o modificar el valor únicamente dentro de la misma clase.', '<?php\nclass Cuenta {\n  private $balance = 500;\n  public function getBalance() {\n    return $this->balance;\n  }\n}\n$miCuenta = new Cuenta();\necho $miCuenta->getBalance();\n?>', 'php');

-- Módulo 22: PHP y MySQL (id_module = 22)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(69, 'Conexión Segura mediante PDO', 'PDO (PHP Data Objects) es la interfaz estándar para interactuar de forma segura con motores de bases de datos. Reemplaza las funciones obsoletas y propensas a fallos de seguridad, encapsulando los parámetros de red e inicio de sesión dentro de un bloque estructurado try-catch para atrapar anomalías.', '<?php\ntry {\n  $pdo = new PDO("mysql:host=localhost;dbname=tienda", "root", "");\n  echo "Conexión exitosa";\n} catch(PDOException $e) {\n  echo "Fallo de conexión: " . $e->getMessage();\n}\n?>', 'php'),
(70, 'Consultas Preparadas', 'Las consultas preparadas son el mecanismo de defensa definitivo contra los ataques informáticos de Inyección SQL. En lugar de concatenar directamente las variables del usuario en el texto de la consulta, se utilizan marcadores de posición anónimos o nombrados (:marcador) que se inyectan de forma aislada en la base de datos.', '<?php\n$stmt = $pdo->prepare("SELECT * FROM productos WHERE categoria = :cat");\n$stmt->execute(["cat" => "tecnologia"]);\n$resultados = $stmt->fetchAll();\n?>', 'php');


-- =========================================================================
-- CURSO 5: NODEJS (id_course = 5) -> code_lang cambiado a 'node'
-- =========================================================================

-- Módulo 24: Express (id_module = 24)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(71, 'Inicializar un Servidor con Express', 'Express es el framework de enrutamiento más extendido para Node.js. Requiere ser importado a nuestro script para luego invocar la inicialización de la aplicación principal. Configuramos un puerto de red específico (por ejemplo, el 3000) en el método de escucha para dejar al servidor listo para recibir peticiones.', 'const express = require("express");\nconst app = express();\n\napp.listen(3000, () => {\n  console.log("Servidor activo en el puerto 3000");\n});', 'node'),
(72, 'Manejo de Rutas Básicas', 'El servidor responde a peticiones de red dirigidas a URLs específicas llamadas rutas. Usamos métodos integrados de Express emparejados con los verbos HTTP correspondientes (como .get()). El callback expone dos objetos cruciales: "req" (los datos que vienen de la petición del cliente) y "res" (los métodos para armar y enviar la respuesta).', 'const express = require("express");\nconst app = express();\n\napp.get("/contacto", (req, res) => {\n  res.send("Formulario de contacto backend.");\n});', 'node');

-- Módulo 25: API REST (id_module = 25)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(73, 'Métodos GET y POST', 'En una API RESTful, el método GET se mapea estrictamente para operaciones de lectura y recuperación segura de datos, sin alterar el estado del sistema. El método POST se utiliza para recibir flujos de información estructurada en el cuerpo de la petición con el objetivo de dar de alta o crear un recurso nuevo.', 'app.get("/api/items", (req, res) => {\n  res.json({ lista: ["item1", "item2"] });\n});\napp.post("/api/items", (req, res) => {\n  res.status(201).json({ status: "Creado" });\n});', 'node'),
(74, 'Métodos PUT y DELETE', 'El método PUT se utiliza para enviar datos de actualización destinados a modificar o reemplazar de forma completa las propiedades de un registro existente en el sistema. El método DELETE se emplea de forma destructiva para ordenar al servidor que remueva un recurso del almacenamiento permanente mediante su identificador único.', 'app.put("/api/items/:id", (req, res) => {\n  const idItem = req.params.id;\n  res.json({ id: idItem, modificado: true });\n});\napp.delete("/api/items/:id", (req, res) => {\n  res.json({ eliminado: true });\n});', 'node'),
(75, 'Códigos de Estado HTTP', 'Los códigos de estado HTTP son respuestas numéricas estandarizadas que el servidor devuelve al cliente para informarle el resultado de una petición. Los bloques principales son: 2xx para éxitos (ej. 200 OK, 201 Created), 4xx para errores del cliente (ej. 400 Bad Request, 404 Not Found), y 5xx para fallos internos del propio servidor.', 'app.get("/api/secreto", (req, res) => {\n  res.status(401).json({ error: "Acceso denegado" });\n});', 'node');

-- Módulo 26: Autenticación (id_module = 26)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(76, 'Hashing de Contraseñas', 'Las contraseñas de los usuarios jamás deben guardarse en texto plano en la base de datos debido a vulnerabilidades catastróficas de seguridad. Se utilizan librerías criptográficas de hashing (como bcrypt) que transforman el texto original en una cadena irreversible, añadiendo además mecanismos de salado.', 'const bcrypt = require("bcrypt");\nasync function cifrar() {\n  const hash = await bcrypt.hash("clave123", 10);\n  console.log(hash);\n}\ncifrar();', 'node'),
(77, 'Generación de JWT (JSON Web Tokens)', 'JWT es un estándar compacto y seguro para transmitir información estructurada en formato JSON entre el cliente y el servidor en sistemas sin estado. Cuando el inicio de sesión es verificado con éxito, el servidor genera un token firmado electrónicamente con una clave secreta para que el cliente lo use en futuras peticiones.', 'const jwt = require("jsonwebtoken");\nconst token = jwt.sign({ id: 50 }, "FIRMA_SECRETA", { expiresIn: "2h" });\nconsole.log(token);', 'node');

-- Módulo 27: WebSockets (id_module = 27)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(78, 'Conexión Inicial Bidireccional', 'A diferencia del protocolo HTTP tradicional basado puramente en peticiones y respuestas puntuales, los WebSockets abren una conexión de red persistente, activa y bidireccional entre el navegador y el servidor en tiempo real. Es ideal para construir aplicaciones instantáneas.', 'const { Server } = require("socket.io");\nconst io = new Server(server_http);\n\nio.on("connection", (socket) => {\n  console.log("Usuario conectado vía WebSocket.");\n});', 'node'),
(79, 'Emisión y Escucha de Eventos', 'La comunicación en WebSockets se basa en un flujo constante de eventos nombrados. El método ".on()" actúa como un receptor permanente que se activa cuando escucha un evento específico enviado por el extremo remoto. El método ".emit()" se utiliza para disparar o enviar paquetes de datos instantáneos.', 'io.on("connection", (socket) => {\n  socket.on("chat_message", (data) => {\n    io.emit("broadcast_message", data);\n  });\n});', 'node');


-- =========================================================================
-- CURSO 6: POSTGRESQL (id_course = 6) -> code_lang cambiado a 'sql'
-- =========================================================================

-- Módulo 29: SELECT (id_module = 29)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(80, 'Proyección de Columnas', 'La sentencia SELECT es el núcleo del lenguaje de consulta SQL en bases de datos relacionales, permitiendo extraer información almacenada en las tablas. En lugar de usar de forma generalizada el asterisco (*), la buena práctica exige especificar explícitamente los nombres de las columnas que requerimos.', 'SELECT first_name, email \nFROM customers;', 'sql'),
(81, 'Filtrado Condicional con WHERE', 'Para restringir la búsqueda y extraer únicamente los registros específicos que cumplen con ciertos criterios de negocio, se acopla la cláusula WHERE. Admite operadores lógicos tradicionales (=, !=, <, >), así como palabras clave especializadas como LIKE o IN.', 'SELECT name, price \nFROM products \nWHERE price > 50.00 AND stock_status = \`available\`;', 'sql'),
(82, 'Ordenamiento con ORDER BY', 'Por naturaleza interna de optimización física de discos, los motores de bases de datos relacionales entregan los registros resultantes de una consulta en un orden impredecible. La cláusula ORDER BY nos permite forzar un ordenamiento explícito bajo una columna, usando los modificadores ASC (ascendente) o DESC (descendente).', 'SELECT username, created_at \nFROM users \nORDER BY created_at DESC \nLIMIT 5;', 'sql');

-- Módulo 30: INSERT, UPDATE y DELETE (id_module = 30)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(83, 'Inserción de Nuevas Filas (INSERT)', 'El comando INSERT INTO se encuadra dentro del subconjunto DML (Lenguaje de Manipulación de Datos) y añade nuevos registros físicos a una tabla. Exige definir entre paréntesis las columnas destino de la tabla y, de forma estrictamente correspondiente en orden y tipo de dato, los valores correspondientes.', 'INSERT INTO employees (first_name, department, salary) \nVALUES (\`Marcos\`, \`Sistemas\`, 3200.50);', 'sql'),
(84, 'Modificación Segura con UPDATE', 'El comando UPDATE altera valores de columnas en registros que ya se encuentran guardados físicamente en la base de datos. ¡Alerta Crítica! Siempre debes acompañar un UPDATE con una cláusula condicional WHERE bien delimitada; si la omites, el motor reescribirá el valor en todas las filas de la tabla de forma irreversible.', 'UPDATE orders \nSET status = \`shipped\` \nWHERE id = 10452;', 'sql'),
(85, 'Borrado de Registros con DELETE', 'El comando DELETE FROM remueve filas completas de una tabla física de datos de forma permanente. Al igual que el comando UPDATE, omitir el filtro selectivo condicional WHERE provocará un desastre operativo, vaciando por completo todo el contenido de la tabla afectada de forma inmediata.', 'DELETE FROM active_sessions \nWHERE expires_at < NOW();', 'sql');

-- Módulo 31: JOINs (id_module = 31)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(86, 'INNER JOIN para Coincidencias Exactas', 'Los JOINs resuelven la esencia relacional de la base de datos combinando columnas de varias tablas vinculadas por llaves primarias y foráneas. Un INNER JOIN evalúa ambas tablas y devuelve estrictamente las filas donde existe una coincidencia perfecta y exacta bajo la condición especificada en la cláusula "ON".', 'SELECT l.id, m.name AS modulo_nombre, l.level \nFROM lessons l\nINNER JOIN modules m ON l.id_module = m.id;', 'sql'),
(87, 'LEFT JOIN para Datos Incompletos', 'La sentencia LEFT JOIN (o Left Outer Join) prioriza de forma absoluta la información de la tabla declarada a la izquierda de la consulta. Devuelve todos sus registros íntegros, y si en la tabla de la derecha no encuentra una fila que coincida con la llave, rellena esos espacios del resultado con valores nulos (NULL).', 'SELECT c.name AS curso, m.name AS modulo \nFROM courses c\nLEFT JOIN modules m ON m.id_course = c.id;', 'sql');

-- Módulo 32: Índices y rendimiento (id_module = 32)
INSERT INTO lesson_content (id_lesson, title, content, code, code_lang) VALUES
(88, 'Creación de Índices Aceleradores (INDEX)', 'Cuando realizas búsquedas frecuentes filtrando por una columna en una tabla millonaria, el rendimiento cae drásticamente. Crear un INDEX genera una estructura de árbol mapeada en memoria (B-Tree por defecto) que permite al motor saltar directamente a la ubicación física del dato sin leer secuencialmente toda la tabla.', 'CREATE INDEX idx_customers_tax_id \nON customers(tax_id);', 'sql'),
(89, 'Análisis de Consultas con EXPLAIN', 'Antes de dar por buena una consulta en entornos de producción masivos, debemos auditar cómo piensa resolverla internamente el planificador de PostgreSQL. Anteponer el comando "EXPLAIN ANALYZE" a nuestra consulta la ejecuta de forma real, devolviendo métricas del costo estimado de CPU, tiempos de ejecución y uso de índices.', 'EXPLAIN ANALYZE \nSELECT * FROM customers \nWHERE tax_id = \`ABC123456\`;', 'sql');