services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: codelive-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - codelive-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: codelive-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/codelive_db
      - PORT=5000
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_NAME=codelive_db
      - JWT_SECRET=tu_clave_secreta_aqui
    depends_on:
      db:
        condition: service_healthy
    networks:
      - codelive-net
    command: node src/index.js

  db:
    image: postgres:latest
    container_name: codelive-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=codelive_db
    volumes:
      - pg-data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - codelive-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: codelive-pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - codelive-net

networks:
  codelive-net:
    driver: bridge

volumes:
  pg-data: